### ISSUE TITLE
新增 map method in set.js

### ISSUE THREAD

**Issue by lucemia** [Tagtoo/Tagtoo_tools#1]
javascript 的 for .. in 會受到 prototype 修改的問題影響

http://stackoverflow.com/questions/728360/most-elegant-way-to-clone-a-javascript-object

http://stackoverflow.com/questions/1963102/what-does-the-jslint-error-body-of-a-for-in-should-be-wrapped-in-an-if-statemen

**Comment by lucemia** [comment]
可以複製 jquery 的 map 方式解決這個問題

**Comment by fkztw** [comment]
https://github.com/Tagtoo/Tagtoo_tools/pull/2
